export class PLPickListItemModel{
OPTM_BINCODE:String ="";
OPTM_CLUSTER_ID:String ="";
OPTM_CONTCODE: String = "";
OPTM_CREATEDATE;
OPTM_CREATEDBY;
OPTM_CUSTOMER_CODE:String = "";
OPTM_ITEMCODE:String = "";
OPTM_MODIFIEDBY:String;
OPTM_MODIFYDATE:String;
OPTM_PICKLIST_BASIS: String;
OPTM_PICKLIST_CODE: String;
OPTM_PICKLIST_ID: Number;
OPTM_PICK_OPER: Number;
OPTM_PICK_TYPE: Number;
OPTM_PLANDATETIME: String;
OPTM_PLANWHSESHIFT_ID: String;
OPTM_PRIORITY: Number;
OPTM_REF_PICKLIST_CODE:String;
OPTM_RESID: String;
OPTM_SHIPMENTID: Number;
OPTM_SOLINE: String;
OPTM_SO_NUMBER:String;
OPTM_STATUS: Number
OPTM_TASK_CODE:String;
OPTM_TOTE_NUMBER: Number;
OPTM_USER_GRP: String;
OPTM_WHSECODE: String;
OPTM_WHSE_ZONE:String;
OPTM_WO_NUMBER: String;
OPTM_PLANDATETIME_Object: Date;
Selected = false;
}