export class PLPickListTaskModel{
OPTM_ACTUALDATETIME: String;
OPTM_BIN_RANGE: String;
OPTM_CREATEDATE:String;
OPTM_CREATEDBY: String;
OPTM_DETAILTYPE: Number;
OPTM_ENDDATETIME: String;
OPTM_GUID: String;
OPTM_INV_TRNSFR_ERROR_DESC: String;
OPTM_INV_TRNSFR_NO: String;
OPTM_INV_TRNSFR_STATUS: String;
OPTM_ITEMCODE: String;
OPTM_MODIFIEDBY: String;
OPTM_MODIFYDATE: String;
OPTM_PICKED_QTY: Number;
OPTM_PLANNEDATETIME: String;
OPTM_PRV_TASKID: Number;
OPTM_RESID: String;
OPTM_RESID_ACT: String;
OPTM_SRC_BIN: String;
OPTM_SRC_BIN_ACT: String;
OPTM_SRC_WHSE: String;
OPTM_SRC_WHSE_ACT: String;
OPTM_STARTDATETIME: String;
OPTM_STATUS: Number;
OPTM_TARGET_BIN: String;
OPTM_TARGET_BIN_ACT: String;
OPTM_TARGET_WHSE: String;
OPTM_TARGET_WHSE_ACT: String;
OPTM_TASKID: Number;
OPTM_TASKTYPE: Number
OPTM_TASK_CODE: String;
OPTM_TASK_QTY: Number
OPTM_TRANSIT_MEANS: Number;
OPTM_USER_GRP: String;
OPTM_VEHICLEUSED:String;
OPTM_WHSE_ZONE:String;
selectedMeansVal: any;

}